Sock.exe: sockDriver.o Socket.o
	g++ sockDriver.cpp Socket.o -o Sock.exe

sockDriver.o: sockDriver.cpp
	g++ -c sockDriver.cpp -o sockDriver.o

Socket.o: Socket.cpp
	g++ -c Socket.cpp -o Socket.o

clean:
	rm *.o Sock.exe