Bitwise.exe: bitDriver.o bitarray.o set.o dictionary.o
	g++ bitDriver.cpp bitarray.o set.o dictionary.o -o Bitwise.exe

bitDriver.o: bitDriver.cpp
	g++ -c bitDriver.cpp -o bitDriver.o

bitarray.o: bitarray.cpp
	g++ -c bitarray.cpp -o bitarray.o

set.o: set.cpp
	g++ -c set.cpp -o set.o

dictionary.o: dictionary.cpp
	g++ -c dictionary.cpp -o dictionary.o

clean:
	rm *.o Bitwise.exe
