Sock.exe: httpMain.o Socket.o request.o
	g++ httpMain.cpp Socket.o request.o -o Sock.exe

httpMain.o: httpMain.cpp
	g++ -c httpMain.cpp -o httpMain.o

Socket.o: Socket.cpp
	g++ -c Socket.cpp -o Socket.o

request.o: request.cpp
	g++ -c request.cpp -o request.o

clean:
	rm *.o Sock.exe